# Generated by Django 5.1.7 on 2025-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Игры')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='games/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Скидка (%)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('platform', models.CharField(choices=[('Switch', 'Nintendo Switch'), ('PS5', 'PlayStation 5'), ('Xbox', 'Xbox Series X')], default='Switch', max_length=50, verbose_name='Платформа')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Издатель')),
                ('genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Игровой картридж',
                'verbose_name_plural': 'Игровые картриджи',
                'ordering': ['-created_at'],
            },
        ),
    ]
